spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://23.229.183.99:3306/spring_test?useSSL=false
    username: testbot
    password: Peru2015neo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect